# Generated by Django 4.2.2 on 2023-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='elearning:/static/elearning/course-default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='elearning:/static/elearning/avatar-default.svg', upload_to=''),
        ),
    ]
