# Generated by Django 4.2.2 on 2023-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_course_image_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/elearning/course-default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='/static/elearning/avatar-default.svg', upload_to=''),
        ),
    ]
