# Generated by Django 4.2.2 on 2023-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_alter_course_image_alter_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='plan',
        ),
    ]
