# Generated by Django 4.2.2 on 2023-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_premieplan_rename_amount_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premieplan',
            name='tag',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
