# Generated by Django 4.2.2 on 2023-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_alter_premieplan_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='premieplan',
            name='daily',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
