# Generated by Django 4.2.2 on 2023-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_alter_payment_course_alter_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='/static/elearning/avatar-default.svg', upload_to='medias/avatar/'),
        ),
    ]
