# Generated by Django 4.2.2 on 2023-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='/static/elearning/avatar-default.svg', upload_to='avatar/'),
        ),
    ]
