# Generated by Django 4.2.2 on 2023-07-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_course', to='elearning.course')),
            ],
        ),
    ]
