# Generated by Django 4.2.1 on 2023-07-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0022_assignment_lesson_submission_resource_grading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="grading",
            name="grader",
        ),
        migrations.RemoveField(
            model_name="grading",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="course",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="user",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Grading",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
