# Generated by Django 4.2.1 on 2023-07-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0024_quiz_course_date_created_quizresult_lesson_files_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Files",
        ),
    ]
