# Generated by Django 4.2.1 on 2023-07-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0025_delete_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Document", "Document"),
                            ("Image", "Image"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="lesson_files/")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.lesson",
                    ),
                ),
            ],
        ),
    ]
