# Generated by Django 4.2.1 on 2023-07-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0026_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
