# Generated by Django 4.2.1 on 2023-07-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0027_course_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
