# Generated by Django 4.2.1 on 2023-07-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0029_alter_course_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="content",
        ),
    ]
