# Generated by Django 4.2.3 on 2023-07-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0029_alter_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.student')),
            ],
        ),
    ]
