# Generated by Django 4.2.1 on 2023-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0030_remove_course_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
