# Generated by Django 4.2.2 on 2023-07-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0030_remove_course_content_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='lesson_videos/'),
        ),
    ]
