# Generated by Django 4.2.3 on 2023-07-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0030_remove_course_content_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerinfo',
            old_name='lesson_id',
            new_name='group_id',
        ),
    ]
