# Generated by Django 4.2.3 on 2023-08-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0030_remove_course_content_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
